from __future__ import annotations

"""Legacy postprocess helper for the completed 邯郸学步 regression sample.

Do not use this for new stories. The reusable path is the project-specific
theme_assets request generated by story_workflow.py.
"""

import subprocess
from pathlib import Path
import time

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont, ImageOps, ImageStat


SRC = Path("/Volumes/语苗计划/外置硬盘/New project/output/imagegen/handan_real")
OUT = Path("/Users/baiyanglin/Desktop/故事剪辑：邯郸学步/04_发布视频/theme_assets")
SAFE_COLOR = (250, 236, 205)
MAX_SOURCE_AGE_SECONDS = 6 * 60 * 60
PLATE_SIZE = (1080, 1440)
PLATE_TOP_H = 360
PLATE_SAFE_H = 608
PLATE_BOTTOM_H = PLATE_SIZE[1] - PLATE_TOP_H - PLATE_SAFE_H


def font(size: int, serif: bool = False) -> ImageFont.ImageFont:
    candidates = (
        [
            "/System/Library/Fonts/Supplemental/Songti.ttc",
            "/System/Library/Fonts/STHeiti Medium.ttc",
            "/Library/Fonts/Arial Unicode.ttf",
        ]
        if serif
        else [
            "/System/Library/Fonts/STHeiti Medium.ttc",
            "/System/Library/Fonts/Hiragino Sans GB.ttc",
            "/Library/Fonts/Arial Unicode.ttf",
        ]
    )
    for path in candidates:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def cover_crop(img: Image.Image, size: tuple[int, int], anchor_y: float = 0.5) -> Image.Image:
    src_w, src_h = img.size
    dst_w, dst_h = size
    scale = max(dst_w / src_w, dst_h / src_h)
    resized = img.resize((round(src_w * scale), round(src_h * scale)), Image.Resampling.LANCZOS)
    x = max(0, (resized.width - dst_w) // 2)
    y = max(0, round((resized.height - dst_h) * anchor_y))
    return resized.crop((x, y, x + dst_w, y + dst_h))


def contain_blur(img: Image.Image, size: tuple[int, int]) -> Image.Image:
    bg = cover_crop(img, size).filter(ImageFilter.GaussianBlur(18))
    fg = ImageOps.contain(img, size, method=Image.Resampling.LANCZOS)
    bg.paste(fg, ((size[0] - fg.width) // 2, (size[1] - fg.height) // 2))
    return bg


def center_text(
    draw: ImageDraw.ImageDraw,
    box: tuple[int, int, int, int],
    text: str,
    fnt: ImageFont.ImageFont,
    fill: tuple[int, int, int],
    stroke_fill: tuple[int, int, int] | None = None,
    stroke_width: int = 0,
) -> None:
    bbox = draw.textbbox((0, 0), text, font=fnt, stroke_width=stroke_width)
    x = box[0] + (box[2] - box[0] - (bbox[2] - bbox[0])) / 2
    y = box[1] + (box[3] - box[1] - (bbox[3] - bbox[1])) / 2 - 4
    draw.text((x, y), text, font=fnt, fill=fill, stroke_fill=stroke_fill, stroke_width=stroke_width)


def fit_font(text: str, width: int, size: int, serif: bool = False) -> ImageFont.ImageFont:
    while size > 20:
        fnt = font(size, serif=serif)
        bbox = ImageDraw.Draw(Image.new("RGB", (10, 10))).textbbox((0, 0), text, font=fnt, stroke_width=6)
        if bbox[2] - bbox[0] <= width:
            return fnt
        size -= 2
    return font(size, serif=serif)


def draw_plate_text(img: Image.Image, variant: str) -> Image.Image:
    img = img.convert("RGBA")
    draw = ImageDraw.Draw(img, "RGBA")
    # Hard production safe strip.
    draw.rectangle((0, 360, 1080, 968), fill=SAFE_COLOR + (255,))

    # Cover model text with polished deterministic text areas.
    # The model is excellent at packaging visuals, but Chinese text can drift, so this central
    # plaque hides generated glyphs and redraws exact production copy.
    draw.rounded_rectangle((54, 18, 1026, 348), radius=42, fill=(255, 230, 164, 228), outline=(139, 72, 42, 210), width=5)
    draw.rounded_rectangle((76, 40, 1004, 326), radius=32, outline=(255, 248, 213, 180), width=3)
    draw.rounded_rectangle((176, 34, 904, 122), radius=36, fill=(205, 82, 48, 245), outline=(255, 216, 128, 255), width=6)
    draw.rounded_rectangle((202, 52, 878, 106), radius=24, outline=(255, 246, 205, 230), width=3)
    headline = "绵羊姐姐讲故事" if variant == "main" else "成语故事"
    center_text(draw, (202, 43, 878, 111), headline, font(46), (255, 248, 220), (111, 54, 32), 2)

    # A warm backing patch ensures any imperfect generated Chinese is hidden.
    draw.rounded_rectangle((170, 136, 910, 248), radius=44, fill=(255, 235, 157, 250), outline=(150, 71, 38, 255), width=7)
    title_f = fit_font("《邯郸学步》", 620, 82, serif=True)
    center_text(draw, (190, 136, 890, 246), "《邯郸学步》", title_f, (255, 249, 184), (134, 57, 33), 7)
    center_text(draw, (190, 136, 890, 246), "《邯郸学步》", title_f, (255, 249, 184), (255, 255, 230), 2)

    badge_f = font(34)
    for box, text, color in [
        ((146, 264, 514, 326), "故事时长 1分53秒", (201, 77, 46, 248)),
        ((566, 264, 934, 326), "适合年龄 3-6岁", (73, 139, 82, 248)),
    ]:
        draw.rounded_rectangle(box, radius=28, fill=color, outline=(255, 231, 158, 255), width=5)
        center_text(draw, box, text, badge_f, (255, 249, 224), (104, 54, 34), 1)

    # Bottom text is already strong in the imagegen source, but redraw for exact wording.
    panel_title = "本期节目资料包" if variant == "main" else "成语故事发布资料"
    lines = ["背景视频 + PPT + 配乐", "文稿 + 标注", "示范视频"]
    draw.rounded_rectangle((138, 1030, 942, 1370), radius=34, fill=(255, 238, 196, 218), outline=(168, 92, 48, 230), width=4)
    draw.text((202, 1060), panel_title, font=font(38), fill=(104, 58, 35), stroke_width=1, stroke_fill=(255, 244, 214))
    line_font = font(48 if variant == "main" else 40)
    for idx, line in enumerate(lines):
        draw.text((228, 1122 + idx * 74), line, font=line_font, fill=(79, 45, 31), stroke_width=1, stroke_fill=(255, 244, 214))
    return img.convert("RGB")


def make_plate(source: str, out_name: str, variant: str) -> None:
    prefix = source.removesuffix("_source.png")
    top = SRC / f"{prefix}_top_source.png"
    bottom = SRC / f"{prefix}_bottom_source.png"
    if top.exists() and bottom.exists():
        top_img = cover_crop(Image.open(top).convert("RGB"), (PLATE_SIZE[0], PLATE_TOP_H), anchor_y=0.5)
        bottom_img = cover_crop(Image.open(bottom).convert("RGB"), (PLATE_SIZE[0], PLATE_BOTTOM_H), anchor_y=0.5)
        img = Image.new("RGB", PLATE_SIZE, SAFE_COLOR)
        img.paste(top_img, (0, 0))
        img.paste(bottom_img, (0, PLATE_TOP_H + PLATE_SAFE_H))
        img.save(OUT / out_name)
        return
    src = Image.open(SRC / source).convert("RGB")
    img = cover_crop(src, PLATE_SIZE, anchor_y=0.5)
    img.save(OUT / out_name)


def plate_source_names(source: str) -> list[str]:
    prefix = source.removesuffix("_source.png")
    top = f"{prefix}_top_source.png"
    bottom = f"{prefix}_bottom_source.png"
    if (SRC / top).exists() and (SRC / bottom).exists():
        return [top, bottom]
    return [source]


def require_fresh_sources(names: list[str]) -> None:
    missing = [name for name in names if not (SRC / name).exists()]
    if missing:
        raise FileNotFoundError("缺少 Codex 原生图像生成源图：" + "、".join(missing))
    now = time.time()
    stale = []
    for name in names:
        path = SRC / name
        age = now - path.stat().st_mtime
        if age > MAX_SOURCE_AGE_SECONDS:
            stale.append(f"{name}（mtime={time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(path.stat().st_mtime))}）")
    if stale:
        raise RuntimeError(
            "拒绝覆盖 theme_assets：源图不是本轮新生成，可能会把旧图误当新图。"
            "请先用当前 Codex 原生图像生成能力生成新的 source 图，再运行后处理。过期源图："
            + "、".join(stale)
        )


def make_background() -> None:
    src = Image.open(SRC / "main_background_16x9_source.png").convert("RGB")
    img = cover_crop(src, (1920, 1080), anchor_y=0.5)
    img.save(OUT / "main_background_16x9.png")


def chroma_to_alpha(img: Image.Image, key=(255, 0, 255), threshold: int = 72) -> Image.Image:
    img = img.convert("RGBA")
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            dist = abs(r - key[0]) + abs(g - key[1]) + abs(b - key[2])
            if dist < threshold or (r > 170 and b > 160 and g < 120):
                px[x, y] = (r, g, b, 0)
            elif r > 140 and b > 135 and g < 145:
                px[x, y] = (r, g, b, max(0, min(a, int((dist - threshold) * 3))))
    return img


def fit_frame_to_window(frame: Image.Image, window: tuple[int, int, int, int]) -> Image.Image:
    """Use the generated full frame, but align it tightly around the story window."""
    frame = frame.convert("RGBA")
    alpha = frame.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        return frame
    x, y, w, h = window
    margin_x = 112
    margin_y = 116
    target = (
        max(0, x - margin_x),
        max(0, y - margin_y),
        min(frame.width, x + w + margin_x),
        min(frame.height, y + h + margin_y),
    )
    subject = frame.crop(bbox)
    fitted = subject.resize((target[2] - target[0], target[3] - target[1]), Image.Resampling.LANCZOS)
    out = Image.new("RGBA", frame.size, (0, 0, 0, 0))
    out.alpha_composite(fitted, (target[0], target[1]))
    return out


def make_frame(source: str, out_name: str, window: tuple[int, int, int, int]) -> None:
    src = Image.open(SRC / source).convert("RGB")
    img = cover_crop(src, (1920, 1080), anchor_y=0.5)
    img = chroma_to_alpha(img)
    img = fit_frame_to_window(img, window)
    img.save(OUT / out_name)


def derive_frame_b_from_a(
    frame_a_path: Path,
    frame_b_path: Path,
    a_window: tuple[int, int, int, int],
    b_window: tuple[int, int, int, int],
) -> None:
    with Image.open(frame_a_path).convert("RGBA") as frame_a:
        ax, ay, aw, ah = a_window
        bx, by, bw, bh = b_window
        scale = min(bw / max(1, aw), bh / max(1, ah))
        scaled = frame_a.resize(
            (max(1, round(frame_a.width * scale)), max(1, round(frame_a.height * scale))),
            Image.Resampling.LANCZOS,
        )
        a_cx = ax + aw / 2
        a_cy = ay + ah / 2
        b_cx = bx + bw / 2
        b_cy = by + bh / 2
        paste_x = round(b_cx - a_cx * scale)
        paste_y = round(b_cy - a_cy * scale)
        frame_b = Image.new("RGBA", frame_a.size, (0, 0, 0, 0))
        frame_b.alpha_composite(scaled, (paste_x, paste_y))
    frame_b.paste(Image.new("RGBA", (bw, bh), (0, 0, 0, 0)), (bx, by))
    # B is a scaled derivative of A; clear tiny canvas corner guards so scaled
    # ornamentation never trips transparent-frame QA at the extreme edges.
    corner = 36
    for box in (
        (0, 0, corner, corner),
        (frame_b.width - corner, 0, frame_b.width, corner),
        (0, frame_b.height - corner, corner, frame_b.height),
        (frame_b.width - corner, frame_b.height - corner, frame_b.width, frame_b.height),
    ):
        frame_b.paste(Image.new("RGBA", (box[2] - box[0], box[3] - box[1]), (0, 0, 0, 0)), box[:2])
    frame_b.save(frame_b_path)


def qa() -> str:
    rows = []
    issues = []
    expected = {
        "main_release_plate.png": (1080, 1440),
        "library_release_plate.png": (1080, 1440),
        "main_background_16x9.png": (1920, 1080),
        "story_frame_a.png": (1920, 1080),
    }
    for name, size in expected.items():
        path = OUT / name
        with Image.open(path) as im:
            note = "ok"
            if im.size != size:
                issues.append(f"{name}: expected {size}, got {im.size}")
                note = "bad size"
            if "release_plate" in name:
                strip = im.crop((0, 360, 1080, 968)).convert("RGB")
                stat = ImageStat.Stat(strip.resize((108, 61)))
                if max(stat.stddev) > 10:
                    issues.append(f"{name}: safe strip is not clean")
                    note = "safe strip issue"
            if "story_frame" in name:
                if im.mode != "RGBA":
                    issues.append(f"{name}: not RGBA")
                    note = "not RGBA"
                alpha = im.getchannel("A")
                box = (210, 270, 1120, 782) if name.endswith("_a.png") else (356, 180, 1565, 860)
                x1, y1, x2, y2 = box
                inset_x = round((x2 - x1) * 0.16)
                inset_y = round((y2 - y1) * 0.16)
                safe_inner = alpha.crop((x1 + inset_x, y1 + inset_y, x2 - inset_x, y2 - inset_y))
                if safe_inner.getbbox() is not None:
                    issues.append(f"{name}: central keyed opening is not transparent")
                    note = "opening alpha issue"
                side_bands = {
                    "top": (x1, max(0, y1 - 120), x2, y1),
                    "bottom": (x1, y2, x2, min(im.height, y2 + 120)),
                    "left": (max(0, x1 - 120), y1, x1, y2),
                    "right": (x2, y1, min(im.width, x2 + 120), y2),
                }
                for label, side_box in side_bands.items():
                    band = alpha.crop(side_box)
                    pixels = max(1, band.width * band.height)
                    visible = sum(1 for value in band.getdata() if value > 24)
                    if visible / pixels < 0.012:
                        issues.append(f"{name}: missing or distant {label} frame side")
                        note = "incomplete frame"
                if any(alpha.getpixel(p) != 0 for p in [(0, 0), (1919, 0), (0, 1079), (1919, 1079)]):
                    issues.append(f"{name}: outer corners are not transparent")
                    note = "corner alpha issue"
            rows.append(f"- {name}: {im.size[0]}x{im.size[1]} {im.mode} {note}")
    report = "\n".join(rows) + ("\n\nAll checks passed." if not issues else "\n\nIssues:\n" + "\n".join(issues))
    (OUT / "theme_assets_qa_report.md").write_text(report, encoding="utf-8")
    return report


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    source_candidates = ["story_frame_source.png", "story_frame_a_source.png"]
    frame_source = next((name for name in source_candidates if (SRC / name).exists()), None)
    if frame_source is None:
        raise FileNotFoundError(f"缺少故事框源图，请提供其中之一：{', '.join(source_candidates)}")
    require_fresh_sources(
        plate_source_names("main_release_plate_source.png")
        + plate_source_names("library_release_plate_source.png")
        + [
            "main_background_16x9_source.png",
            frame_source,
        ]
    )
    make_plate("main_release_plate_source.png", "main_release_plate.png", "main")
    make_plate("library_release_plate_source.png", "library_release_plate.png", "library")
    make_background()
    cover_crop(Image.open(SRC / frame_source).convert("RGB"), (1920, 1080), anchor_y=0.5).save(OUT / "story_frame_source.png")
    make_frame(frame_source, "story_frame_a.png", (210, 270, 910, 512))
    print(qa())


if __name__ == "__main__":
    main()
